// client/src/app/transaction-form/transaction-form.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { BlockchainNodeService } from '../shared/services';

@Component({
  selector: 'app-transaction-form',
  templateUrl: './transaction-form.component.html'
})
export class TransactionFormComponent {
  readonly transactionForm: FormGroup;

  constructor(readonly node: BlockchainNodeService, fb: FormBuilder) {
    this.transactionForm = fb.group({
      sender   : ['', Validators.required],
      recipient: ['', Validators.required],
      amount   : ['', Validators.required]
    });
  }

  enqueueTransaction() {
    if (this.transactionForm.valid) {
      this.node.addTransaction(this.transactionForm.value);
      this.transactionForm.reset();
    }
  }
}
<h2>New transaction</h2>
<form class="add-transaction-form"
      [formGroup]="transactionForm"
      (ngSubmit)="enqueueTransaction()">
  <input type="text"
         name="sender"
         autocomplete="off"
         placeholder="Sender"
         formControlName="sender">

  <span class="hidden-xs">→</span>

  <input type="text"
         name="recipient"
         autocomplete="off"
         placeholder="Recipient"
         formControlName="recipient">

  <input type="number"
         name="amount"
         autocomplete="off"
         placeholder="Amount"
         formControlName="amount">

  <button type="submit"
          class="ripple"
          [disabled]="transactionForm.invalid || node.isMining">ADD TRANSACTION</button>
</form>

// client/src/components/TransactionForm.tsx
import React, { ChangeEvent, FormEvent, useState } from "react";
import { Transaction } from "../lib/blockchain-node"

interface TransactionFormProps {
  onAddTransaction: (transaction: Transaction) => void;
  disabled: boolean;
}

const defaultFormValue = {
  recipient: '',
  sender: '',
  amount: 0,
};

export const TransactionForm: React.FC<TransactionFormProps> = ({onAddTransaction, disabled}) => {
  const [formValue, setFormValue] = useState<Transaction>(defaultFormValue);
  const isValid = formValue.sender && formValue.recipient && formValue.amount > 0;

  function handleInputChange({target}: ChangeEvent<HTMLInputElement>) {
    setFormValue({
      ...formValue,
      [target.name]: target.value
    })
  }

  function handleFormSubmit(event: FormEvent) {
    event.preventDefault();
    onAddTransaction(formValue);
    setFormValue(defaultFormValue);
  }

  return (
    <>
      <h2>New transaction</h2>
      <form className="add-transaction-form" onSubmit={handleFormSubmit}>
        <input
          type="text"
          name="sender"
          placeholder="Sender"
          autoComplete="off"
          disabled={disabled}
          value={formValue.sender}
          onChange={handleInputChange}
        />
        <span className="hidden-xs">→</span>
        <input
          type="text"
          name="recipient"
          placeholder="Recipient"
          autoComplete="off"
          disabled={disabled}
          value={formValue.recipient}
          onChange={handleInputChange}
        />
        <input
          type="number"
          name="amount"
          placeholder="Amount"
          disabled={disabled}
          value={formValue.amount}
          onChange={handleInputChange}
        />
        <button
          type="submit"
          disabled={!isValid || disabled}
          className="ripple"
        >ADD TRANSACTION</button>
      </form>
    </>
  )
}
